#-----------------------------------------------------------------------------%
# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/
#-----------------------------------------------------------------------------%

.PHONY: realclean
realclean:
	# Remove installed library
	rm -rf lib
